apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: glc5jbfb1-nodejs-gitops
  description: This is GitOps manifest for glc5jbfb1-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=glc5jbfb1-nodejs
    backstage.io/kubernetes-id: glc5jbfb1-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: glc5jbfb1-nodejs
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:glc5jbfb1-nodejs
